name: Prueba Self-Hosted Runner

on:
  push:

jobs:
  comprobar-token:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: powershell
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if ($env:DEV_TOKEN -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "DEV_TOKEN y LOCAL_DEV_TOKEN coinciden correctamente."
          }
          else {
            Write-Host "DEV_TOKEN y LOCAL_DEV_TOKEN NO coinciden."
            exit 1
          }